const express = require("express");
const routes = require("./routes");
const passport = require("passport");
const session = require("express-session");

const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.use(
  session({
    //This secret password was generated by using secure password generation sites.
    secret: "bRaH6$mPyXLg/J='",
    resave: false,
    saveUninitialized: true,
  })
);

require("./config/passport");

app.use(passport.initialize());
app.use(passport.session());

app.use(routes);

app.listen(3000, () => {
  console.log("Server started on port 3000");
});
